/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args){

        Mobile mobile = new Mobile("mobile","red","brandNull");
        mobile.makeCall("hi");
        System.out.print("\n");
        System.out.print(mobile.getBasicInfo());

        System.out.print("\n-------------\n");

        iPhone iphone = new iPhone("mobile","red","iPhone");
        iphone.makeCall("hi");
        System.out.print("\n");
        System.out.print(iphone.getBasicInfo());

        System.out.print("\n-------------\n");

        Android android = new Android("mobile","red","Adnroid");
        android.makeCall("hi");
        System.out.print("\n");
        System.out.print(android.getBasicInfo());

        System.out.print("\n-------------\n");

        Person personA = new Person(android);
        personA.makeCall("-----------------------");

        System.out.print("\n-------------\n");

        Person personB = new Person(iphone);
        personB.makeCall("-------------------------------------------------------");


        System.out.print("\n-------------\n");

        IPhoneRobot iPhoneRobot = new IPhoneRobot(iphone);
        iPhoneRobot.makeCall("-------------------------------------------------------");

        System.out.print("\n-------------\n");
        personB.setMobile(android);
        System.out.print(personB.getBasicInfo());


    }
}
