/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args){

        Mobile mobile = new Mobile("mobile","red","brandNull");
        mobile.makeCall("hi");

        System.out.print("\n-------------\n");

        Mobile iphone = new iPhone("mobile","red","brandNull");
        iphone.makeCall("hi");

        System.out.print("\n-------------\n");

        Mobile android = new Android("mobile","red","brandNull");
        android.makeCall("hi");
    }
}
